import streamlit as st
import math
#import json

# zadani hodnot
H = st.number_input("Velikost mrizky v 1. kvadrantu H (10.0 az 500.0 po 0.1) [mm]", key="H", value=75.0, min_value=10.0, max_value=500.0, step=0.1, format="%0.1f")
R = st.number_input("Zaobleni rohu R (0.0 az 100.0 po 0.1) [mm]", key="R", value=35.0, min_value=0.0, max_value=100.0, step=0.1, format="%0.1f")
krok = st.number_input("Krok mrizky (0.1 az 10.0 po 0.1) [mm]", key="krok", value=0.9, min_value=0.1, max_value=10.0, step=0.1, format="%0.1f")
tloustka = st.number_input("Tloustka car (0.1 az 1.0 po 0.1) [mm]", key="tloustka", value=0.2, min_value=0.1, max_value=1.0, step=0.1, format="%0.1f")

# tlacitko pro prepocet zadanych hodnot a vystup do souboru
generuj = st.button("Generuj rastr_py.dxf", key="Generuj rastr.dxf")
if generuj:
    H = H // krok * krok
    R = R // krok * krok
    S = H - R
    tloustka = tloustka * 100

# kontrola spravnosti hodnot pred vystupem do souboru
    st.write(f"Prepoctene hodnoty pro vystup do souboru:")
    st.write(f"H: {H}")
    st.write(f"R: {R}")
    st.write(f"krok: {krok}")
    st.write(f"tloustka: {tloustka}")
    st.write(f"S = H - R: {S}")

# vystup do souboru
    st.write("Vytvarim soubor: rastr_py.dxf")

# cilovy soubor hlavicka
    with open("rastr_py.dxf", "w", encoding="utf-8") as f:
        f.write(f"0\n")
        f.write(f"SECTION\n")
        f.write(f"2\n")
        f.write(f"HEADER\n")
        f.write(f"0\n")
        f.write(f"ENDSEC\n")
        f.write(f"0\n")
        f.write(f"SECTION\n")
        f.write(f"2\n")
        f.write(f"TABLES\n")
        f.write(f"0\n")
        f.write(f"ENDSEC\n")
        f.write(f"0\n")
        f.write(f"SECTION\n")
        f.write(f"2\n")
        f.write(f"BLOCKS\n")
        f.write(f"0\n")
        f.write(f"ENDSEC\n")
        f.write(f"0\n")
        f.write(f"SECTION\n")
        f.write(f"2\n")
        f.write(f"ENTITIES\n")

# cilovy soubor prvni cyklus
        dolnimez = 0
        prirustek = round(10 * krok)
        hornimez = round(10 * S) + prirustek
        for i in range (dolnimez, hornimez, prirustek):
# nejdelsi vodorovne
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"-{H}\n")
            f.write(f"20\n")
            f.write(f"{i/10}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{H}\n")
            f.write(f"21\n")
            f.write(f"{i/10}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"-{H}\n")
            f.write(f"20\n")
            f.write(f"{-i/10}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{H}\n")
            f.write(f"21\n")
            f.write(f"{-i/10}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
# nejdelsi svisle
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"{i/10}\n")
            f.write(f"20\n")
            f.write(f"-{H}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{i/10}\n")
            f.write(f"21\n")
            f.write(f"{H}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"{-i/10}\n")
            f.write(f"20\n")
            f.write(f"-{H}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{-i/10}\n")
            f.write(f"21\n")
            f.write(f"{H}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
        #Next i

# cilovy soubor druhy cyklus
        dolnimez = round(10 * krok)
        prirustek = round(10 * krok)
        hornimez = round(10 * R) + prirustek
        for i in range (dolnimez, hornimez, prirustek):
            n = i / 10
            m = math.sqrt(R * R - n * n)
# promenlive vodorovne
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"{-S - m}\n")
            f.write(f"20\n")
            f.write(f"{S + i/10}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{S + m}\n")
            f.write(f"21\n")
            f.write(f"{S + i/10}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"{-S - m}\n")
            f.write(f"20\n")
            f.write(f"{-S - i/10}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{S + m}\n")
            f.write("21\n")
            f.write(f"{-S - i/10}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
# promenlive svisle
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"{S + i/10}\n")
            f.write(f"20\n")
            f.write(f"{-S - m}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{S + i/10}\n")
            f.write(f"21\n")
            f.write(f"{S + m}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
            f.write(f"0\n")
            f.write(f"LINE\n")
            f.write(f"8\n")
            f.write(f"0\n")
            f.write(f"10\n")
            f.write(f"{-S - i/10}\n")
            f.write(f"20\n")
            f.write(f"{-S - m}\n")
            #f.write(f"30\n")
            #f.write(f"0\n")
            f.write(f"11\n")
            f.write(f"{-S - i/10}\n")
            f.write(f"21\n")
            f.write(f"{S + m}\n")
            #f.write(f"31\n")
            #f.write(f"0\n")
            f.write(f"370\n")
            f.write(f"{tloustka}\n")
        #Next i

# cilovy soubor konec
        f.write(f"0\n")
        f.write(f"ENDSEC\n")
        f.write(f"0\n")
        f.write(f"SECTION\n")
        f.write(f"2\n")
        f.write(f"OBJECTS\n")
        f.write(f"0\n")
        f.write(f"ENDSEC\n")
        f.write(f"0\n")
        f.write(f"EOF\n")

        st.write(f"Soubor vytvoren.")

        st.link_button("Jdi na rastr_py.dxf", "https://adak-rastr.streamlit.app.rastr_py.dxf")

        #st.down
        #st.download_button(
        #label="Download rastr_py.dxf",
        #data=file,
        #file_name="rastr_py.dxf",
        #)
